#Even Fibonacci numbers

=begin
Each new term in the Fibonacci sequence is generated by adding
the previous two terms. By starting with 1 and 2,
the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence
whose values do not exceed four million,
find the sum of the even-valued terms.
=end

def even_fib(first, second)
  return 0 if first > 4000000
  return first % 2 == 0 ? first + even_fib(second, second + first) : even_fib(second, second + first)
end

puts even_fib(1,2)
